// simple list of instrument names available
export default [
  'violin',
  'viola',
  'cello',
  'contrabass',
  'flute',
  'trumpet',
  'flugelhorn',
  'french horn',
  'trombone',
  'tuba',
  'oboe',
  'bassoon',
  'clarinet',
  'bass clarinet',
  'saxophone',
  'baritone saxophone',
  'marimba',
  'xylophone',
];
